[package]
name = "leg-cpu-emulator"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.86"
yeet-ops = "1.0.0"
regex = "1.10.6"
once_cell = "1.19.0"
strum = "0.26.3"
strum_macros = "0.26.4"